//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class DefaultAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func usersGet(completion: @escaping ((_ data: InlineResponse200?,_ error: Error?) -> Void)) {
        usersGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     - GET /users
     - sample
     - examples: [{contentType=application/json, example={
  "firstName" : "temil",
  "lastName" : "temil",
  "userUUid" : "113a3d8d-ddac-4b0f-9f16-15123512",
  "email" : "ts@smartbear.com"
}}]

     - returns: RequestBuilder<InlineResponse200> 
     */
    open class func usersGetWithRequestBuilder() -> RequestBuilder<InlineResponse200> {
        let path = "/users"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<InlineResponse200>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
