//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class InlineResponse200: Codable {

    /** ID from DB */
    public var userUUid: UUID
    /** user email from DB */
    public var email: String
    /** users first name */
    public var firstName: String
    /** users last name */
    public var lastName: String


    public init(userUUid: UUID, email: String, firstName: String, lastName: String) {
        self.userUUid = userUUid
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(userUUid, forKey: "userUUid")
        try container.encode(email, forKey: "email")
        try container.encode(firstName, forKey: "firstName")
        try container.encode(lastName, forKey: "lastName")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        userUUid = try container.decode(UUID.self, forKey: "userUUid")
        email = try container.decode(String.self, forKey: "email")
        firstName = try container.decode(String.self, forKey: "firstName")
        lastName = try container.decode(String.self, forKey: "lastName")
    }
}

